Feature/add transform from json
sharp-rmf/fleet_driver_mir pull request #11
Opened 2022-03-16 07:02 UTC by alphonsustay

Features added are as follows:

1) MIR and RMF respective Coordinate Reference Points are now loaded from the JSON file instead of hardcoded into `fleet_driver_mir.py` 

2) Under ` path_following_closure()`, additional logic was added to aid the robot with a multi-floor deployment setup. When the next point given is not on the same floor level as the robot, a floor map change mission, preconfigured on the MiR, will be triggered. This is in accordance with a typical multi-floor deployment of MiR without RMF. When the robot's level and the point floor level match, the latest floor level map transform will be loaded and the robot will be sent to the desired point.

2022-03-22 04:37 UTC, mxgrey approved these changes
Thanks for contributing these changes! I don't have access to a MiR myself, so I can't test it out, but the changes all look sensible to me, and I trust that you've tested them on an actual MiR.

I just left a few remarks on some of the inline comments which I think can probably be removed from the PR.

2022-03-22 04:37 UTC, mxgrey commented on fleet_driver_mir/fleet_driver_mir.py
> +                    ## ISSUES
Can I check what this `## ISSUES` comment is meant for?

2022-03-22 04:37 UTC, mxgrey commented on fleet_driver_mir/fleet_driver_mir.py
> +## TODO: Physical testing of the current code implementation to be done [23/10/21]
Since this date is in October of last year, is it safe to assume that the physical testing was performed and we can remove this comment?

2022-03-22 04:37 UTC, mxgrey commented on fleet_driver_mir/fleet_driver_mir.py
> +##       Within function, robot transform and current map variables must be updated.
It looks to me like a map change feature has been added, starting on line 115. Is this comment perhaps out of date?

2022-03-24 05:32 UTC, mxgrey requested changes
Thanks for removing the outdated comments! I did notice there's an addition of one line that I think is misplaced. Please see my comment below.

2022-03-24 05:32 UTC, mxgrey commented on fleet_driver_mir/fleet_driver_mir.py
> +                            return
It looks like this `return` call was added inside the braces of `self.parent.get_logger().error( ... `. I believe that's a syntax error. Was this line added by mistake, or was it meant to be inside of the `except KeyError:` block but after the error logging?

2022-03-24 05:47 UTC, alphonsustay commented on fleet_driver_mir/fleet_driver_mir.py
> +                            return
Oh was added by mistake, it should be outside the braces. Thank you for spotting that Grey. Will make the changes now.

2022-03-24 06:48 UTC, mxgrey approved these changes

2022-03-24 06:49 UTC, merged